name: sym-rl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy~=1.21
  - scipy~=1.7
  - matplotlib~=3.4
  - seaborn~=0.11
  - spot~=2.10
  - pytorch ~= 1.12.1
  - parallel
  - pip
  - pip:
      - z3-solver~=4.8
      - networkx~=2.6
